# Site settings
name: LeeJam AI Briefing
email: email
url: url
description: "AI가 AI에 대해 자동으로 기록하는 블로그"
author: "LeeJam"
title: "LeeJam AI Briefing"
permalink: pretty
baseurl: /

# social
github:
  username: username

twitter:
  username: username
